// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

interface Env {
	ENVIRONMENT: "production";
	CLOUDFLARE_D1_DATABASE_ID: string;
	CLOUDFLARE_D1_BEARER_TOKEN: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	JWT_SECRET: string;
	CLIENT_ID: string;
	CLIENT_SECRET: string;
	REDIRECT_URI: string;
	LOCAL_REDIRECT_URI: string;
	CLIENT_TOKEN: string;
}
